x-airflow-common: &airflow-common
  image: apache/airflow:3.1.0
  environment: &airflow-common-env
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    # # Forcing Airflow to use the shared DB
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_shared/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_DOT_ENV: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: 'true'
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 120
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    PYTHONPATH: "/opt/airflow"
    DOCKER_HOST: "unix:///var/run/docker.sock"
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/tasks:/opt/airflow/tasks
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/requirements.txt:/opt/airflow/requirements.txt
    - ${AIRFLOW_PROJ_DIR:-.}/.env:/opt/airflow/.env
    - ${AIRFLOW_PROJ_DIR:-.}/config.ini:/opt/airflow/config.ini
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    postgres_shared:
      condition: service_healthy

services:
# ====== 1. QDRANT ======
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    hostname: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT_API_KEY: qdrant_api_key
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks: [lakehouse]

# ====== 2.MINIO ======
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks: [lakehouse]

# ====== 3. SHARED DATABASE======
  postgres_shared:
    image: postgres:16
    container_name: postgres_shared
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5433:5432"
    command: [ "postgres", "-c", "wal_level=logical" ]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - shared-pg-data:/var/lib/postgresql/data
      # Map nguyên thư mục chứa các file SQL của bạn
      - ./postgresscripts:/docker-entrypoint-initdb.d
    restart: always
    networks: [lakehouse]


    # ====== 4. HIVE METASTORE ======
  hive-metastore:
    image: 'starburstdata/hive:3.1.2-e.18'
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
      - "9083:9083"
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      # Forcing Hive to use the shared DB
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres_shared:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3a://warehouse/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: password
      S3_PATH_STYLE_ACCESS: "true"
      METASTORE_TYPE: postgres
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      postgres_shared:
        condition: service_healthy
    networks: [lakehouse]

  # ====== 5. TRINO ======
  trino-coordinator:
    image: trinodb/trino:400
    container_name: trino-coordinator
    ports:
      - "9090:8080"
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      - hive-metastore
      - minio
    networks: [lakehouse]

  # ====== 6. DELTA + SPARK ======
  delta-spark:
    image: deltaio/delta-docker:4.0.0
    container_name: delta-spark
    command: [ "bash", "-lc", "sleep infinity" ]
    environment:
      TZ: Asia/Ho_Chi_Minh
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
      SPARK_PACKAGES: io.delta:delta-spark_2.13:4.0.0,org.apache.hadoop:hadoop-aws:3.4.1
      SPARK_OPTS: >
        --conf spark.jars.ivy=/home/NBuser/.ivy2
        --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
        --conf spark.hadoop.fs.s3a.access.key=admin
        --conf spark.hadoop.fs.s3a.secret.key=password
        --conf spark.hadoop.fs.s3a.path.style.access=true
        --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false
        --conf spark.hadoop.fs.s3a.endpoint.region=us-east-1
        --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
        --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
        --conf spark.sql.catalogImplementation=hive
        --conf spark.hadoop.hive.metastore.uris=thrift://hive-metastore:9083
        --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
        --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
    volumes:
      - ./spark/jobs:/opt/jobs
    depends_on:
      - minio
      - hive-metastore
    networks: [lakehouse]

  # ====== 7. AIRFLOW SERVICES ======
  airflow-apiserver:
    <<: *airflow-common
    container_name: airflow-apiserver
    command: ["airflow", "api-server"]
    ports: ["8800:8080"]
    restart: always
    networks: [lakehouse]

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: ["airflow", "scheduler"]
    restart: always
    networks: [lakehouse]

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    command: ["airflow", "dag-processor"]
    restart: always
    networks: [lakehouse]

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: ["airflow", "triggerer"]
    restart: always
    networks: [lakehouse]

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    user: "50000:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -eu
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/tasks /opt/airflow/plugins /opt/airflow/config
        export PATH="/home/airflow/.local/bin:$PATH"
        
        # Install requirements if file exists and is not a directory
        if [ -f /opt/airflow/requirements.txt ] && [ ! -d /opt/airflow/requirements.txt ]; then
          echo "Installing Python packages from requirements.txt..."
          pip install --no-cache-dir -r /opt/airflow/requirements.txt
        else
          echo "Warning: requirements.txt not found or is a directory. Installing default packages..."
          pip install --no-cache-dir minio pandas requests configparser
        fi
        
        airflow db migrate
        airflow users create \
          --username "$$_AIRFLOW_WWW_USER_USERNAME" \
          --password "$$_AIRFLOW_WWW_USER_PASSWORD" \
          --firstname Air \
          --lastname Flow \
          --role Admin \
          --email admin@example.org || true
        echo "Airflow init done."
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    depends_on:
      <<: *airflow-common-depends-on
    networks: [lakehouse]

  airflow-cli:
    <<: *airflow-common
    container_name: airflow-cli
    profiles: [debug]
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command: [ "bash", "-c", "airflow" ]
    depends_on:
      <<: *airflow-common-depends-on
    networks: [lakehouse]


networks:
  lakehouse:
    name: lakehouse

volumes:
  minio-data: {}
  shared-pg-data: {}
  qdrant-data: {}
